language: node_js
node_js:
  - 10
script: yarn ci
install:
  - yarn install --frozen-lockfile --non-interactive
cache:
  yarn: true
branches:
  only:
    - master
dist: trusty
notifications:
  email: false
before_install:
  # Enable user namespace cloning
  - "sysctl kernel.unprivileged_userns_clone=1"
  # Launch XVFB
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
addons:
  apt:
    packages:
      # This is required to run new chrome on old trusty
      - libnss3
